name: "macos"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - uses: ./
    - name: Run Playwright
      run: cd sample && npm install && node index.js
    - name: Check browsers
      run: ls ~/Library/Caches/ms-playwright/
    - name: Cache browsers
      uses: actions/cache@v1
      with:
        path: '~/Library/Caches/ms-playwright/'
        key: ${{ runner.os }}-browsers
